kind: ServiceAccount
apiVersion: v1
metadata:
  name: restart-worker-coredns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-worker-coredns
  namespace: kube-system
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: ["coredns"]
    verbs: ["get", "patch"]
---
# bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-worker-coredns
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: restart-worker-coredns
subjects:
  - kind: ServiceAccount
    name: restart-worker-coredns
    namespace: kube-system
