apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppeteer
  namespace: shift
  labels:
    app: puppeteer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puppeteer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: puppeteer
    spec:
      containers:
        - name: puppeteer
          image: ghcr.io/puppeteer/puppeteer:16.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: puppeteer
          resources:
            requests:
              memory: "400M"
              cpu: "0.3"
            limits:
              memory: "1G"
              cpu: "1"
