name: Docker - Build Base Image

on:
  workflow_dispatch:
    inputs:
      docker-image-version:
        description: 'Docker Image Version'
        required: true
        default: '1.1.0-php-8-1-alpine'

jobs:
  build-base-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up branch
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/BaseDockerfile
          push: true
          tags: keshavpudaruthshift/shift-edge:base-${{ inputs.docker-image-version }}
          build-args: |
            VERSION=${{ inputs.docker-image-version }}
